export const dummyProducts = [
  {
    id: 1,
    title: "Vintage Leather Bag",
    price: "₹899",
    category: "Accessories",
    image: "https://via.placeholder.com/150",
    description: "Classic bag with minimal wear and eco charm.",
  },
  {
    id: 2,
    title: "Pre-loved Denim Jacket",
    price: "₹1,299",
    category: "Clothing",
    image: "https://via.placeholder.com/150",
    description: "Stylish and sustainable denim jacket in excellent condition.",
  },
  {
    id: 3,
    title: "Refurbished Smartphone",
    price: "₹12,999",
    category: "Electronics",
    image: "https://via.placeholder.com/150",
    description: "Fully functional smartphone with 1-year warranty.",
  },
  {
    id: 4,
    title: "Handcrafted Ceramic Planter",
    price: "₹499",
    category: "Home Decor",
    image: "https://via.placeholder.com/150",
    description: "Beautiful ceramic planter for your indoor plants.",
  },
  {
    id: 5,
    title: "Vintage Vinyl Records Collection",
    price: "₹2,499",
    category: "Music",
    image: "https://via.placeholder.com/150",
    description: "Collection of 20 classic vinyl records from the 70s and 80s.",
  },
  {
    id: 6,
    title: "Wooden Coffee Table",
    price: "₹3,999",
    category: "Furniture",
    image: "https://via.placeholder.com/150",
    description: "Solid wood coffee table with minimal signs of use.",
  },
  {
    id: 7,
    title: "Classic Literature Book Set",
    price: "₹1,499",
    category: "Books",
    image: "https://via.placeholder.com/150",
    description: "Collection of 10 classic literature books in good condition.",
  },
  {
    id: 8,
    title: "Vintage Film Camera",
    price: "₹5,999",
    category: "Electronics",
    image: "https://via.placeholder.com/150",
    description: "Fully functional vintage film camera with original case.",
  },
]
